### ISSUE TITLE
Error à l'import de fbx

### ISSUE THREAD

**Issue by Impre-visible** [fbx/freebox-qtcreator-plugin#10]
Je ne sais pas pk, mais j'ai cette erreur 
![image](https://user-images.githubusercontent.com/69050895/190557954-150dd8c9-a9ff-48f3-9659-e990fc4b9805.png)
![image](https://user-images.githubusercontent.com/69050895/190558034-d3917a23-b681-4a1f-8983-f60ae640341e.png)
j'ai pourtant suivi le tuto pour l'installation sous Windows 10, mais ce soucis fait que je ne peux pas edit l'interface de l'app

**Comment by Aymkdn** [comment]
J'ai moi aussi des erreurs, mais au final ça fonctionne quand même normalement : 
![image](https://user-images.githubusercontent.com/946315/190576898-6ec438c6-7be1-409a-925a-55d1593be51c.png)

**Comment by Impre-visible** [comment]
alors je ne sais pas trop comment changer le design de l'app ducoup. Une piste ?

**Comment by Aymkdn** [comment]
Aucune idée, désolé.

**Comment by rawoul** [comment]
Bonjour,
Les erreurs sont normales, étant donné que le code de la bibliothèque freebox utilisée sur la box n’est pas livré avec le plugin.

que voulez vous dire par « changer le design de l’application » ?

**Comment by Impre-visible** [comment]
> Bonjour, Les erreurs sont normales, étant donné que le code de la bibliothèque freebox utilisée sur la box n’est pas livré avec le plugin.
> 
> que voulez vous dire par « changer le design de l’application » ?

je veux dire "changer le design" ajouter des champs de texte, boutons etc...

**Comment by Aymkdn** [comment]
Tu vas voir, c'est bien galère… Tu peux regarder un peu du côté de ces exemples : https://github.com/fbx/qmlapps_examples

Bon courage 😅

**Comment by Impre-visible** [comment]
merci
