### ISSUE TITLE
Erreur de compilation sur tout projets

### ISSUE THREAD

**Issue by Pascal66** [fbx/freebox-qtcreator-plugin#3]
Fontconfig error: Cannot load default config file
◾ Application instance does not declare a handleUrl() function !

◾ Settings load failed with error:  QJsonObject({"code":-32000,"message":"Network error: Hôte inaccessible"})

**Comment by AcK77** [comment]
Bonjour,
La solution est d'ajouter les "capabilities" dans le manifest.json de votre projet QML.
- net_lan: accès au réseau local.
- net_wan: accès à internet.
- net_gw: accès au Freebox Server.
- gw_settings: FreeboxOS, accès aux paramètres.
- gw_contacts: FreeboxOS, accès à la liste des contacts.
- gw_calls: FreeboxOS, accès à la liste des appels.
- gw_explorer: FreeboxOS, accès aux disques.
- gw_downloader: FreeboxOS: accès au downloader.
- gw_parental: FreeboxOS: accès au controle parental.
- gw_pvr: FreeboxOS: accès aux enregistrements.

Exemple : 
"capabilities": { 
        "net_wan": "required" 
}

**Comment by ghost** [comment]
La réponse de AcK77 ne résoud pas le problème cité par Pascal66. Les messages d'erreur sont toujours les mêmes après avoir ajouté les "capabilities"

**Comment by be1** [comment]
Bonjour,
Les deux messages sont sans importance pour le fonctionnement de vos applications.

Pour le premier message _handleUrl()_ voir : https://dev.freebox.fr/sdk/manifest.html au paragraphe «Comment traîter une URL au lancement»

Pour le second message, il s'agit des _Settings_ qui, pour le moment, ne sont pas encore fonctionnels pour les applications tierces.
