### ISSUE TITLE
version QTCreator/Plugin

### ISSUE THREAD

**Issue by bb2k** [fbx/freebox-qtcreator-plugin#5]
Bonjour,

J'ai voulu jeter un oeil au SDK pour la freebox et il s'avère que QTcreator 4.3 n'est plus distribué et que le plugin freebox n'est pas compatible avec les versions disponibles. 

Il serait peut être préférable de mettre tout le SDK à jour si vous désiréz un communauté active sur freebox.

Bonne journée

**Comment by titoftit** [comment]
Bonjour, 

Je suis au même point que toi ... J'ai quand même trouvé QTCreator 4.3, mais j'ai beaucoup de mal à le faire fonctionner.

Pas étonnant qu'il y a très peu de plugin dispo ... c'est dommage.

**Comment by camarade35** [comment]
+1 à part freiner les personnes motivées, il n'y a aucune volonté
j'ai passé mon après midi à tenter des choses, sans résultat
M Niel vous souhaitez être ouvert, faites des MAJ
QTCreator 4.3 dispo ici : https://download.qt.io/archive/qt/

**Comment by rcoscali** [comment]
J'ai déployer l'env de dev. Il faut un qt5 (j'ai pris 5.12.5), qt-creator v4.3.0 et un llvm/clang pour tous les outils de manip de code qui sont tres utils. La version est LLVM 7 (branche release_70) une version autour de mai/juin 2018. J'ai pris un arbre à moi mais je pense que la release 7.0.0 ici: https://releases.llvm.org/download.html#7.0.0
devrait fonctionner parfaitement.
Ca fait beaucoup de chose à compiler mais ensuite tous fonctionne nickel.

**Comment by mdamien** [comment]
J'ai aussi réussi à faire tourner le SDK en compilant [QtCreator 4.3](https://github.com/qt-creator/qt-creator/archive/4.3.zip) avec Qt 5.9 (paquet `qt5-default`).

Bonus: J'ai mis le tout déjà pré-compilé dans une image docker (500M): https://drive.google.com/file/d/1rNeE7ibv23KtfulrDQKN56pCNQR_8jDh/view?usp=sharing

```console
> docker load < freebox-sdk.tar.gz
> sudo xhost local:root # pour que X puisse se connecter à docker
> docker run -it -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --net=host --privileged me/qtcreator /opt/qt-creator-4.3/bin/qtcreator
```

Et voilà le résultat en vidéo: https://www.youtube.com/watch?v=gz9fPqsJIvg

**Comment by bb2k** [comment]
trop vieux=)
